### ISSUE TITLE
[Error: Input file is missing] on absolute URL requests

### ISSUE THREAD

**Issue by tomgreeEn** [fast-average-color/fast-average-color-node#7]
I recently updated from node 10 to 14(.18.1) and updated to the recent release of fast-average-color-node around the same and now I get this error if I try to process a file by absolute URL string, which I believe comes from Sharp: `[Error: Input file is missing]`

Example absolute URLs which are failing:
https://test.io/wp-content/uploads/2019/02/testIO-logo-rgb-2.png
https://onlinejpgtools.com/images/examples-onlinejpgtools/sunflower.jpg

It works as expected with local files and Base64 encoded strings.

Has anyone else had this?

**Comment by hcodes** [comment]
Absolute urls are not supported.

Example of using with `node-fetch`:
https://github.com/node-fetch/node-fetch#buffer

**Comment by tomgreeEn** [comment]
Thanks. Strangely I somehow had this working with absolute URLs previously. 
But the #buffer solution works great now. Thanks!

**Comment by Bejasc** [comment]
This definitely works with Absolute URLs when targeting `1.0.3` 

@hcodes Why the change?

**Comment by hcodes** [comment]
It happened because of the change of dependencies. Absolute urls were supported in `canvas`, but not in `sharp'.
v2.0: `canvas` replaced with `sharp` package for Apple M1 support.

If you need support for absolute urls, please create a Issue or PR.

**Comment by Bejasc** [comment]
It would be good if this sort of breaking change could be communicated in future. 

I cannot find any reference to support being removed for this through `fast-average-color-node`

Thanks, I will create an Issue now.
