### ISSUE TITLE
Re-introduce support for Absolute URLs

### ISSUE THREAD

**Issue by Bejasc** [fast-average-color/fast-average-color-node#9]
I understand that on the upgrade from `canvas` to `sharp`, support was lost for Absolute URLs. 

When targeting version `1.0.3` of this package, the following works without issue.

```ts
const avgColor = await getAverageColor("https://raw.githubusercontent.com/fast-average-color/fast-average-color/master/img/title.png");
```

However, updating to[ 2.0.0](https://github.com/fast-average-color/fast-average-color-node/releases/tag/v2.0.0), this is no longer possible, and produces the following error.
`[Error: Input file is missing]`

---

Please restore this functionality, or provide migration steps so that this is still possible through `fast-average-color-node` as it once was. 

Also see: #7

**Comment by hcodes** [comment]
v2.2.0
